apiVersion: v1
kind: ConfigMap
metadata:
  name: init-sql
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS books (
        Id SERIAL PRIMARY KEY,
        Name TEXT NOT NULL,
        Description TEXT
    );
    INSERT INTO books (Name, Description) VALUES
    ('Atomic Habits', 'Tiny Changes, Remarkable Results.'),
    ('Emotional Intelligence', 'Why It can matter more than IQ.'),
    ('Limitless', 'Upgrade Your Brain, Learn Anything faster.'),
    ('The Psychology of Money', 'Timeless lessons on wealth, greed, and happiness.'),
    ('Ikigai', 'The Japanese Secret to a Long and happy Life.');